server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:msauthdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.uuid}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    home-page-url-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: secret
